webserver_log_file = "webserver.log"
manage_log_file = "manage.log"
scheduler_log_file = ""
log_level = "INFO"
worker_hashrate_fold = 86400
stage = false

site_title = "SimpleMulti"
# the FQDN
site_url = "http://www.simplemulti.com"
coin_name = "Multi"
# host for static assets e.g. {assets_address}/css/main.css
assets_address = "/static"
# logo img
logo = "/img/logo.png"
site_meta_desc = "A custom mining pool with automatic exchanging between currencies, no registration, and a focus on developing new tools for miners"
# Default values for new miner config
default_stratum_url = "stratum+tcp://stratum.simplemulti.com"
default_stratum_port = "3363"
charge_autoex_fees = false


[main_cache]
type = "redis"

[redis_conn]
type = "redis"

[mining_servers.default]
display = true

[currencies.default]
buyable = false
sellable = false
mineable = false
trans_confirmations = 6
block_mature_confirms = 120

[currencies.BTC]
name = "Bitcoin"
algo = "sha256"
address_version = [0, 5]
block_time = 120

[currencies.RBY]
name = "Rubycoin"
algo = "scrypt"
address_version = [61]
block_time = 150

[currencies.BTM]
name = "Bitmark"
algo = "scrypt"
address_version = [85]
block_time = 120
block_mature_confirms = 720

[currencies.DRK]
name = "Darkcoin"
algo = "x11"
address_version = [76]
block_time = 120

[currencies.URO]
name = "Urocoin"
algo = "x11"
address_version = [68]
block_time = 120

[currencies.DOGE]
name = "Dogecoin"
algo = "scrypt"
address_version = [30]
block_time = 60

[currencies.SYS]
name = "Syscoin"
algo = "scrypt"
address_version = [63]
block_time = 60

[currencies.PTC]
name = "Pesetacoin"
algo = "scrypt"
address_version = [47]
block_time = 60

[currencies.TCO]
name = "Tacocoin"
algo = "scrypt"
address_version = [48]
block_time = 60

[currencies.ULTC]
name = "Umbrella-LTC"
algo = "scrypt"
address_version = [68]
block_time = 600

[currencies.LTC]
name = "Litecoin"
algo = "scrypt"
address_version = [48]
block_time = 600

[currencies.VTC]
name = "Vertcoin"
algo = "scryptn"
address_version = [71]
block_time = 150

[currencies.MON]
name = "Monocle"
algo = "scryptn"
address_version = [50]
block_time = 120

[currencies.GRE]
name = "Greencoin"
algo = "scrypt"
address_version = [38]
block_time = 60

[currencies.FRAC]
name = "Fractalcoin"
algo = "x11"
address_version = [36]
block_time = 60

[currencies.START]
name = "Startcoin V2"
algo = "x11"
address_version = [125]
block_time = 60

[currencies.CANN]
name = "Cannabiscoin"
algo = "x11"
address_version = [28]
block_time = 42

[currencies.VIA]
name = "Viacoin"
algo = "scrypt"
address_version = [71]
block_time = 24
block_mature_confirms = 3600

[currencies.FTC]
name = "Feathercoin"
algo = "scrypt"
address_version = [14]
block_time = 60

[currencies.WDC]
name = "Worldcoin"
algo = "scrypt"
address_version = [73]
block_time = 30

[currencies.ANC]
name = "Anoncoin"
algo = "scrypt"
address_version = [23]
block_time = 205

[currencies.MEC]
name = "Megacoin"
algo = "scrypt"
address_version = [50]
block_time = 150

[currencies.EMC2]
name = "Einsteiniumcoin"
algo = "scrypt"
address_version = [33]
block_time = 60


[algos.x11]
hashes_per_share = 4294967296
normalize_mult = 0.181818182
display = "X11"

[algos.scryptn]
hashes_per_share = 65536
normalize_mult = 2.127659574
display = "Scrypt-N"

[algos.scrypt]
hashes_per_share = 65536
normalize_mult = 1
display = "Scrypt"

[[navbar.left_nav]]
title = "Home"
icon = "home"
link = "/"
active_key = "home"

[[navbar.left_nav]]
title = "Getting Started"
icon = "cog"
link = "/configuration_guide"
active_key = "config"

[[navbar.left_nav]]
title = "User Stats"
icon = "user"
link = "/stats"
active_key = "stats"

[[navbar.left_nav]]
title = "Pool Stats"
icon = "life-ring"
link = "/pool_stats"
active_key = "pool_stats"

[[navbar.left_nav]]
title = "Leaderboard"
icon = "bar-chart-o"
link = "/leaderboard"
active_key = "leaderboard"

[[navbar.left_nav]]
title = "Extras"
icon = "star"
link = "#"
active_key = ""
[[navbar.left_nav.dropdown]]
title = "Simple Crypto Website"
icon = "globe"
link = "http://www.simplecryptogroup.com"
[[navbar.left_nav.dropdown]]
title = "Source Code"
icon = "github"
link = "http://www.github.com/simplecrypto/simplecoin_multi"

[[navbar.right_nav]]
title = "Contact Us"
icon = "bullhorn"
link = "#"
active_key = ""
[[navbar.right_nav.dropdown]]
title = "Email"
icon = "envelope"
link = "mailto:simplecryptogroup@gmail.com"
[[navbar.right_nav.dropdown]]
title = "IRC"
icon = "comments"
link = "https://kiwiirc.com/client/irc.freenode.net/#simplecrypto"
[[navbar.right_nav.dropdown]]
title = "Reddit"
icon = "reddit"
link = "http://www.reddit.com/r/simplecrypto"
[[navbar.right_nav.dropdown]]
title = "Github"
icon = "github"
link = "http://www.github.com/simplecrypto/"
