pool_payout_currency = "LTC"
SECRET_KEY = "somethting_really_secret"
SQLALCHEMY_DATABASE_URI = "sqlite:///database.sqlite3"
DEBUG = true
rpc_signature = "test"

[chains.1]
title = "Litecoin + SYS MM"
algo = "scrypt"
type = "pplns"
last_n = 2
fee_perc = "0.01"

[locations.CA]
location_acronym = "CA"
location = "Beauharnois, Canada"
country_flag = "/img/ca.svg"
address = "http://localhost"

[currencies.LTC]
sellable = true
buyable = true
mineable = true
pool_payout_addr = "LbfSCZE1p9A3Yj2JK1n57kxyD2H1ZSXtNG"
[currencies.LTC.coinserv]
port = 20001
address = "127.0.0.1"
username = "admin1"
password = "123"

[currencies.SYS]
mineable = true
pool_payout_addr = "SdzKyvhD2Y3xJvGVSfx96NXszq6x9BZX34"
[currencies.SYS.coinserv]
port = 19001
address = "127.0.0.1"
username = "admin1"
password = "123"

[mining_servers.1]
address = "localhost"
monitor_address = "http://localhost:3855/stratum"
port = 3333
location = "CA"
diff = 1
chain = 1
