pool_payout_currency = "BTC"
SECRET_KEY = "somethting_really_secret"
SQLALCHEMY_DATABASE_URI = "sqlite://"
DEBUG = true
rpc_signature = "test"

[redis_conn]
type = "mock_redis"

[main_cache]
type = "mock_redis"

[chains.2]
title = "Vertcoin"
algo = "scryptn"
type = "prop"
last_n = 2
fee_perc = "0.01"

[chains.1]
title = "Dogecoin"
algo = "scrypt"
type = "pplns"
currencies = ["DOGE"]
last_n = 2
fee_perc = "0.01"

[locations.CA]
location_acronym = "CA"
location = "Beauharnois, Canada"
country_flag = "/img/ca.svg"
address = "http://ca.simplemulti.com"

[currencies.BTC]
buyable = true
pool_payout_addr = "1LmZN5ifbHdQy5jW9wNqyTuke3odY2Zos8"
[currencies.BTC.coinserv]
username = ""
password = ""
port = 1
address = ""

[currencies.TCO]
mineable = true
pool_payout_addr = "LUMPrhhWnoTfNXnDNWyqGG355fjTUVzFYX"
[currencies.TCO.coinserv]
username = ""
password = ""
port = 1
address = ""

[currencies.DOGE]
sellable = true
buyable = true
mineable = true
[currencies.DOGE.coinserv]
username = ""
password = ""
port = 1
address = ""

[mining_servers.1]
address = "localhost"
monitor_address = "http://localhost:3855/stratum"
port = 3333
location = "CA"
diff = 512
chain = 1
